Develop
ArtemKrotenok/MJC-School-Gift-Certificates-System pull request #1
Opened 2022-01-20 13:42 UTC by ArtemKrotenok

2022-01-20 19:07 UTC, andrey7067 requested changes

2022-01-20 19:07 UTC, andrey7067 commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> +@Slf4j
You added a logger, but you don't use it

2022-01-20 19:07 UTC, andrey7067 commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> + */
Move the documentation up

2022-01-20 19:07 UTC, andrey7067 commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> +        }
Try to rewrite

2022-01-21 12:50 UTC, ArtemKrotenok commented on repository-module/src/main/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImpl.java
> +        if (giftCertificateList.size() > 0) {
fixed

2022-01-21 13:03 UTC, ArtemKrotenok commented on repository-module/src/main/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImpl.java
> +            giftCertificate.setTagList(getTagListForCertificate(giftCertificate));
fixed

2022-01-21 13:06 UTC, ArtemKrotenok commented on service-module/src/main/java/com/epam/esm/service/imp/GiftCertificateServiceImpl.java
> +        if (page == null || page < 0) {
fixed

2022-01-21 13:26 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> + */
fixed

2022-01-21 13:31 UTC, ArtemKrotenok commented on service-module/src/main/java/com/epam/esm/service/util/GiftCertificateUtil.java
> +    public static final String DATE_PATTERN = "yyyy-MM-dd'T'HH:mm:ss.SSS";
I don't need it, but the author of the task really needs it: "CreateDate, LastUpdateDate - format ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601). Example: 2018-08-29T06:12:15.156."

2022-01-21 13:35 UTC, ArtemKrotenok commented on service-module/src/main/java/com/epam/esm/service/imp/TagServiceImpl.java
> +        if (page < 0) {
fixed

2022-01-21 13:36 UTC, ArtemKrotenok commented on service-module/src/main/java/com/epam/esm/service/imp/TagServiceImpl.java
> +    private String getErrorValid(Long id) {
fixed

2022-01-21 13:55 UTC, KristinaPotapovich commented on service-module/src/main/java/com/epam/esm/service/imp/GiftCertificateServiceImpl.java
> +    private static final int FIST_PAGE = 1;
Please correct the word "FIRST"

2022-01-24 10:59 UTC, ArtemKrotenok commented on repository-module/src/main/java/com/epam/esm/repository/impl/GiftCertificateTagRepositoryImpl.java
> +                .stream().findAny().orElse(null);
fixed

2022-01-24 11:04 UTC, ArtemKrotenok commented on service-module/src/main/java/com/epam/esm/service/util/GiftCertificateUtil.java
> +    public static final String DATE_PATTERN = "yyyy-MM-dd'T'HH:mm:ss.SSS";
fixed

2022-01-24 11:23 UTC, ArtemKrotenok commented on web-module/src/test/java/com/epam/esm/repository/TagRepositoryTest.java
> +    void findById_validId_tag() {
fixed

2022-01-24 11:39 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/TagController.java
> +    public ResponseEntity<Object> creatTag(@RequestBody TagDTO tagDTO) {
fixed

2022-01-24 11:42 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/TagController.java
> +@RequestMapping(value = "/api/certificate/tag", produces = MediaType.APPLICATION_JSON_VALUE)
fixed

2022-01-24 11:50 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> +    @GetMapping("/search")
fixed

2022-01-24 14:04 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> +    @GetMapping("/search")
+ rewrote search logic

2022-01-24 14:06 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> +    public ResponseEntity<Object> getGiftCertificateByPageSorted(@RequestParam(name = "page", required = false) Integer page) {
fixed

2022-01-24 14:12 UTC, ArtemKrotenok commented on service-module/src/main/java/com/epam/esm/service/imp/GiftCertificateServiceImpl.java
> +    private static final int FIST_PAGE = 1;
fixed

2022-01-24 14:16 UTC, ArtemKrotenok commented on service-module/src/main/java/com/epam/esm/service/imp/TagServiceImpl.java
> +    private List<TagDTO> checkAndReturnResult(List<Tag> tagList) throws GiftCertificateServiceException {
fixed

2022-01-26 11:50 UTC, ArtemKrotenok commented on service-module/src/test/java/com/epam/esm/service/GiftCertificateServiceTest.java
> +        Exception exception = assertThrows(Exception.class, () -> {
fixed

2022-01-26 11:51 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> +        }
fixed

2022-01-26 11:51 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> +@RequestMapping(value = "/api/certificate", produces = MediaType.APPLICATION_JSON_VALUE)
fixed

2022-01-26 12:21 UTC, ArtemKrotenok commented on web-module/src/main/java/com/epam/esm/app/controller/api/GiftCertificateController.java
> +@RestController
fixed

2022-01-26 13:39 UTC, ArtemKrotenok commented on service-module/src/main/java/com/epam/esm/service/imp/GiftCertificateServiceImpl.java
> +        if (errorValidMessage != null) {
fixed

2022-02-07 07:19 UTC, merged